### ISSUE TITLE
Rviz for melodic version

### ISSUE THREAD

**Issue by DhayaShekar** [osrf/rvizweb#25]
RVizWeb is not working for melodic version of ROS.Catkin_make install is failing.

**Comment by jubeira** [comment]
Hi @DhayaShekar; `roswww` hasn't been released for Melodic AFAIK, which is a required dependency. Once it is released we can check whether some other action is required to make it work.

**Comment by DhayaShekar** [comment]
Thanq.

**Comment by dirk-thomas** [comment]
> Catkin_make install is failing.

Please include the exact error message you are getting.

**Comment by athackst** [comment]
I'm also using melodic.  I can share the melodic dockerfile I used to do an initial check out if that's useful.

I had to grab the source for roswww, interactive_marker_proxy and depthcloud_encoder.

**Comment by dirk-thomas** [comment]
> I had to grab the source for roswww, interactive_marker_proxy and depthcloud_encoder.

I would suggest to fill tickets upstream requesting a Melodic release.

**Comment by jubeira** [comment]
Ticket tracking (thanks @athackst!):
- [x] [roswww](https://github.com/tork-a/roswww/issues/47) - Melodic PR: https://github.com/ros/rosdistro/pull/20641.
- [x] [depthcloud_encoder](https://github.com/RobotWebTools/depthcloud_encoder/issues/13) - Melodic PR: https://github.com/ros/rosdistro/pull/20774.
- [x] [interactive_marker_proxy](https://github.com/RobotWebTools/interactive_marker_proxy/issues/2) - Melodic PR: https://github.com/ros/rosdistro/pull/20773.

___________________________________________________________________

@DhayaShekar one small clarification: you can try running `rvizweb` in a Docker container using the docker image in the repository (see [instructions](https://github.com/osrf/rvizweb#rvizweb-in-a-docker-container)). If you need it outside the container, then you will need those dependencies from source as pointed out above.

**Comment by jubeira** [comment]
@chapulina all the deps already have a PR open in `rosdistro` and will probably be merged soon. Would you please create a `-release` repository for `rvizweb` to use it with Bloom?

**Comment by chapulina** [comment]
> Would you please create a -release repository for rvizweb to use it with Bloom?

@dirk-thomas created one, you should have all permissions: https://github.com/ros-gbp/rvizweb-release

**Comment by jubeira** [comment]
See https://github.com/osrf/rvizweb/issues/27#issuecomment-480425186; for now a binary release into melodic is not possible because of system dependency issues.
